server:
    port: 8080

spring:
    profiles: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            databaseName: hartjes
    

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003



# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: nl.jworks.hartjes
      domain: nl.jworks.hartjes.domain
      restdto: nl.jworks.hartjes.web.rest.dto
    liquibase:
      defaultCatalogName: 
      defaultSchema: 
    watchdir:
      - target/classes
